### ISSUE TITLE
GApps removal script?

### ISSUE THREAD

**Issue by Primokorn** [CHEF-KOCH/Remove-Gapps#1]
Hi,

I understand the need of a script to remove Google stuff on a stock firmware but what's the point of creating such a script for a GApps package.
The easiest way would be to *NOT* flash it after installing a custom ROM...

Thank you.

**Comment by danban359** [comment]
Seriously?

Cause some of us messed up and would like to correct that mistake. Did you expect some sort of profound answer?

**Comment by Primokorn** [comment]
Yes the answer is to not flash any Gapps package. I still don't understand why he created this.
Chef-Koch is maybe too busy to monitor his own repos...

**Comment by vamsi2405** [comment]
wait!? so this doesnt remove anthing from stock roms?
