### ISSUE TITLE
Causes bootloop on mido running RR v5.8.0

### ISSUE THREAD

**Issue by asymcon** [CHEF-KOCH/Remove-Gapps#6]
Wiped dalvik, cache after install - no good. 
Wanted to remove pico GApps from Redmi Note 4 (mido) running ResurrectionRemix.
After installing, phone gets stuck on boot.
Reverted system partition to previous state and it boots fine.

**Comment by CHEF-KOCH** [comment]
You have to flash a ROM after the removal processor or you need to flash another alternative package like nogapps etc. otherwise you will get stuck on the boot process. It's mentioned in the readme (which no one reads).
